### ISSUE TITLE
diff: Return number of function evaluations from finite difference functions?

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/diff#29]

**Comment by btracey** [comment]
I don't think that's necessary. It's very predictable, isn't it? Are you thinking about adding to the number of calls in optimize?

**Comment by vladimir-ch** [comment]
Yes, it's kind of predictable, the number of evaluations implicitly follows from the method. I think that we should explicitly write the number in the docs. I wanted to know your opinion.

And yes, I was having optimize in mind even though I think it would be nice if we didn't mix the stats from the method itself and from fd approximations. Speaking of optimize, we will need to provide a mechanism for calling Gradient and/or Hessian that sets OriginKnown and Value.

**Comment by btracey** [comment]
If we want to support this, I think it should be implemented with functions. For example, `func HessianEvals(stencil Stencil, originKnown bool) int`.

Feel free to re-open this issue in the main repository if you think it's still a good idea.
